### ISSUE TITLE
Cookbook file definitions/default.rb has a ruby syntax error

### ISSUE THREAD

**Issue by dkmichaels** [jrwesolo/limits#3] opened 2015-01-18 23:10 UTC
I did a knife cookbook site install limits, then tried to upload to my hosted chef server. It failed with error:

 knife cookbook upload limits
Uploading limits         [1.0.0]
FATAL: Cookbook file definitions/default.rb has a ruby syntax error:
FATAL: /common/opt/provisioning-hex/chef-repo/cookbooks/limits/definitions/default.rb:1: syntax error, unexpected ':', expecting $end
FATAL: define :set_limit, use_system: false, # ~FC015
FATAL:                               ^

I did not edit this file at all.

**Comment by dkmichaels** [comment] 2015-01-18 23:10
I'm on Ubuntu 12.04 LTS and 
# knife --version
Chef: 11.6.0

**Comment by jrwesolo** [comment] 2015-03-08 21:34
Hello @dkmichaels!

I seem to be unable to replicate your issue. I installed Chef 11.6.0 to try and see if I got the same results:

```bash
$ knife --version
Chef: 11.6.0
```

```bash
$ knife cookbook site install limits
Installing limits to /Users/jrwesolo/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-limits
Downloading limits from the cookbooks site at version 1.0.0 to /Users/jrwesolo/cookbooks/limits.tar.gz
Cookbook saved: /Users/jrwesolo/cookbooks/limits.tar.gz
Removing pre-existing version.
Uncompressing limits version 1.0.0.
removing downloaded tarball
1 files updated, committing changes
Creating tag cookbook-site-imported-limits-1.0.0
Checking out the master branch.
Updating 6f934f3..7037d26
Fast-forward
 limits/.gitignore                          |  15 +++++++++
 limits/.kitchen.yml                        |  26 ++++++++++++++
 limits/.rubocop.yml                        |   7 ++++
 limits/.rubocop_todo.yml                   |  10 ++++++
 limits/Berksfile                           |   8 +++++
 limits/CHANGELOG.md                        |  26 ++++++++++++++
 limits/LICENSE                             |  21 ++++++++++++
 limits/README.md                           | 197 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 limits/attributes/default.rb               |   5 +++
 limits/chefignore                          |  95 ++++++++++++++++++++++++++++++++++++++++++++++++++++
 limits/definitions/default.rb              |  31 +++++++++++++++++
 limits/libraries/default.rb                |  50 +++++++++++++++++++++++++++
 limits/libraries/matchers.rb               |  13 +++++++
 limits/metadata.json                       |  45 +++++++++++++++++++++++++
 limits/metadata.rb                         |  15 +++++++++
 limits/providers/config.rb                 |  53 +++++++++++++++++++++++++++++
 limits/resources/config.rb                 |   6 ++++
 limits/templates/default/limits.d.conf.erb |  19 +++++++++++
 18 files changed, 642 insertions(+)
 create mode 100755 limits/.gitignore
 create mode 100755 limits/.kitchen.yml
 create mode 100755 limits/.rubocop.yml
 create mode 100644 limits/.rubocop_todo.yml
 create mode 100644 limits/Berksfile
 create mode 100644 limits/CHANGELOG.md
 create mode 100644 limits/LICENSE
 create mode 100644 limits/README.md
 create mode 100644 limits/attributes/default.rb
 create mode 100644 limits/chefignore
 create mode 100644 limits/definitions/default.rb
 create mode 100644 limits/libraries/default.rb
 create mode 100644 limits/libraries/matchers.rb
 create mode 100644 limits/metadata.json
 create mode 100644 limits/metadata.rb
 create mode 100644 limits/providers/config.rb
 create mode 100644 limits/resources/config.rb
 create mode 100644 limits/templates/default/limits.d.conf.erb
Cookbook limits version 1.0.0 successfully installed
```

```bash
$ knife cookbook upload limits
Uploading limits         [1.0.0]
Uploaded 1 cookbook.
```

I'm not sure what it could be, but I don't see any issues currently with the default.rb file in definitions. What version of ruby are you using?

**Comment by dkmichaels** [comment] 2015-04-21 18:03
ruby -version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

**Comment by jrwesolo** [comment] 2015-06-25 17:17
This is likely caused by the old ruby version. 1.8.7 is no longer supported by Chef 12 and was marked EOL June 2013. I'd recommend using ChefDK for your development work as it comes bundled with a known good ruby version. Do you have any restrictions that will keep you from moving to ChefDK or, at minimum, a newer version of ruby? I am going to go ahead and close this, but feel free to comment and we can continue the discussion.

**Closed by jrwesolo** 2015-06-25 17:17 UTC
